### ISSUE TITLE
There is no license here

### ISSUE THREAD

**Issue by rkdarst** [coderefinery/jekyll-common#14]
This license doesn't have a license, and I don't know the history of it.

**Comment by bast** [comment]
Working on it ...

**Comment by bast** [comment]
README says:

The code under `assets/` and `includes/` has been copied from
https://github.com/carpentries/styles which is copyright
[Software Carpentry](https://software-carpentry.org)
and provided under a [CC-BY-4.0 license](https://github.com/carpentries/styles/blob/gh-pages/LICENSE.md).

**Comment by bast** [comment]
However, I don't think CC-BY is relevant here and the text should have mentioned MIT which covers the code part. I will adjust the README, add a LICENSE file and ping all people who have contributed to this for their agreement.
