### ISSUE TITLE
Add a "quick reference" or "cheatsheet" link to the top navigation

### ISSUE THREAD

**Issue by rkdarst** [coderefinery/jekyll-common#4]
There is now a consistent top navigation that says "Lesson | Credit and license | Instructor guide".  Could we add a consistent quick ref/cheatsheet link there too?

I see where it would be added, my main question is how to do so while not having broken links for lessons that aren't updated yet.  I don't see conditional for if it exists yet, but don't entirely know how jekyll works...

**Comment by bast** [comment]
Good idea. I will add that.

**Comment by bast** [comment]
You want this for Git intro? (as a first demo)

**Comment by rkdarst** [comment]
git-intro is what I am working on now and my first use case... no
promises that I'll get the quick ref done today though.

**Comment by bast** [comment]
Would this be a markdown document that is linked? (then I can set up a stub and you could expand on that)

**Comment by rkdarst** [comment]
What do you think is best?  Maybe even make it an arbitrary link, some
may be markdown txt file, some may be jekyll page, some may be PDF
links, etc.

**Comment by bast** [comment]
OK I will see what can be done. It's easy if we assume the presence of a specific file but I agree that flexibility would be nice.

**Comment by rkdarst** [comment]
Then let's go for easy method: assume presence of a file.  That file
can link to other material if needed.  What do you think?

**Comment by bast** [comment]
Sounds good, let's go for that as a start. I will send a PR this afternoon.

**Comment by bast** [comment]
I will close this in a moment but also requires a tweak on the Git intro side, I will send a PR for that.

**Comment by bast** [comment]
In my understanding this is now in place. Closing.
