### ISSUE TITLE
"test your knowledge" is hidden until you click it, it confused me

### ISSUE THREAD

**Issue by rkdarst** [coderefinery/jekyll-common#5]
Seen in git-intro, but posting here.  Minor issue, priority is low.

In part it's because my desktop blocks javascript by default, so defaulted to expanded and I wasn't expecting it to be hidden.  I also thought I saw one "test your knowledge" that was already expanded, but wasn't.

Could be nice to have the "test your knowledge" boxes expanded by default, but only solutions hidden.  Maybe this is a usage thing, maybe an upstream thing.

**Comment by bast** [comment]
Solved in 922ad7461b56ee0b71506419ba1bdd36560ef45d.
